# Generated by Django 4.2 on 2026-02-26 20:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('OWNER', 'Dueño'), ('CHIEF', 'Jefe de Patio'), ('OPERATOR', 'Operador'), ('DISPATCHER', 'Despachador')], max_length=20)),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fantasia', models.CharField(max_length=100)),
                ('rut_empresa', models.CharField(max_length=20, unique=True)),
                ('usa_despachador', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tonelaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_combustible', models.CharField(max_length=20)),
                ('unidad_medida', models.CharField(choices=[('HORAS', 'Horas'), ('KM', 'Kilómetros')], max_length=10)),
                ('valor_actual_medida', models.DecimalField(decimal_places=2, max_digits=15)),
                ('consumo_teorico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proximo_mantenimiento', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En Ruta'), ('TALLER', 'En Taller')], default='DISPONIBLE', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrada', models.DateTimeField(blank=True, null=True)),
                ('medida_salida', models.DecimalField(decimal_places=2, max_digits=15)),
                ('medida_entrada', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('nro_guia_despacho', models.CharField(max_length=50)),
                ('despachador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_despacho', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.maquinaria')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_operador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('precio_promedio_ponderado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='GPSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitud', models.DecimalField(decimal_places=9, max_digits=12)),
                ('velocidad', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.maquinaria')),
            ],
        ),
        migrations.CreateModel(
            name='CompraCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField()),
                ('nro_factura', models.CharField(max_length=50)),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_litro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CombustibleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_carga', models.CharField(choices=[('INTERNA', 'Carga Interna'), ('EXTERNA', 'Estación Servicio')], max_length=20)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('medida_al_cargar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.maquinaria')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveles_ok', models.BooleanField(default=True)),
                ('luces_ok', models.BooleanField(default=True)),
                ('estructura_ok', models.BooleanField(default=True)),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.maquinaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
