# Generated by Django 4.2 on 2026-02-26 21:52

from django.db import migrations, models
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', gestion.models.UsuarioManager()),
            ],
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='nro_guia_despacho',
            field=models.CharField(help_text='Número de documento emitido por comercial/vendedor', max_length=50),
        ),
    ]
