# Generated by Django 4.2 on 2026-02-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En Ruta'), ('TALLER', 'En Taller'), ('VENDIDA', 'Vendida'), ('DESUSO', 'En Desuso')], default='DISPONIBLE', max_length=20),
        ),
    ]
