# Generated by Django 4.2 on 2026-02-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_maquinaria_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LICENCIA', 'Licencia Médica'), ('VACACIONES', 'Vacaciones'), ('DESVINCULADO', 'Desvinculado'), ('OTRO', 'Otro / No Disponible')], default='DISPONIBLE', max_length=20),
        ),
    ]
