# Generated by Django 4.2 on 2026-02-28 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_usuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='operador_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
