# Generated by Django 4.2 on 2026-02-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_maquinaria_operador_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='combustiblelog',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='combustiblelog',
            name='tipo_documento',
            field=models.CharField(blank=True, help_text='Ej: Factura, Boleta, Guía (o en blanco si es interna)', max_length=50, null=True),
        ),
    ]
