# Generated by Django 4.2 on 2026-02-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_combustiblelog_numero_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combustiblelog',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='combustiblelog',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, help_text='OT opcional al momento de cargar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.ordentrabajo'),
        ),
    ]
