# Generated by Django 4.2 on 2026-02-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_combustiblelog_fecha_carga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('OWNER', 'Dueño'), ('CHIEF', 'Jefe de Patio'), ('OPERATOR', 'Operador'), ('DISPATCHER', 'Despachador (Portería)'), ('FUEL', 'Cargador Combustible'), ('MECHANIC', 'Mecánico / Taller')], max_length=20),
        ),
    ]
