# Generated by Django 4.2 on 2026-02-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='tipo',
            field=models.CharField(choices=[('RETROEXCAVADORA', 'Retroexcavadora'), ('EXCAVADORA', 'Excavadora'), ('CARGADOR_FRONTAL', 'Cargador Frontal'), ('MOTONIVELADORA', 'Motoniveladora'), ('RODILLO', 'Rodillo Compactador'), ('MINICARGADOR', 'Minicargador'), ('HORQUILLA', 'Grúa Horquilla'), ('CAMIONETA', 'Camioneta'), ('AUTOMOVIL', 'Automóvil'), ('GRUA', 'Grúa Pluma'), ('CAMION', 'Camión'), ('OTRO', 'Otro')], default='OTRO', max_length=50),
        ),
    ]
