# Generated by Django 4.2 on 2026-03-01 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_maquinaria_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'Preventivo (Por Horómetro/Km)'), ('CORRECTIVO', 'Correctivo (Por Falla/Rotura)'), ('RUTINARIO', 'Revisión Diaria / Rutinaria')], max_length=20)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('ESPERANDO_REPUESTO', 'Esperando Repuesto'), ('FINALIZADO', 'Finalizado')], default='EN_PROCESO', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('medida_ingreso', models.DecimalField(decimal_places=2, help_text='Horómetro o KM al entrar al taller', max_digits=10)),
                ('medida_salida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion_falla', models.TextField(help_text='Motivo de ingreso o falla reportada')),
                ('trabajo_realizado', models.TextField(blank=True, help_text='Detalle de las reparaciones efectuadas', null=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, help_text='Suma de mano de obra y repuestos', max_digits=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_taller', to='gestion.maquinaria')),
                ('mecanico', models.ForeignKey(limit_choices_to={'rol__in': ['MECHANIC', 'CHIEF', 'OWNER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
