# Generated by Django 4.2 on 2026-03-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_ordentaller'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modulo_checklist',
            field=models.BooleanField(default=True, help_text='Inspecciones Diarias'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_combustible',
            field=models.BooleanField(default=False, help_text='Gestión y Cargas'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_gps',
            field=models.BooleanField(default=False, help_text='Rastreo Telemétrico'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_mantencion',
            field=models.BooleanField(default=False, help_text='Taller y Mantenimiento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_reporteria',
            field=models.BooleanField(default=False, help_text='Exportación a PDF/Excel'),
        ),
    ]
