# Generated by Django 4.2 on 2026-03-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_empresa_modulo_checklist_empresa_modulo_combustible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True, help_text='Soft Delete: Define si la empresa tiene acceso al sistema.'),
        ),
    ]
