# Generated by Django 4.2 on 2026-03-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_empresa_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='combustiblelog',
            name='sello_flujometro',
            field=models.BigIntegerField(blank=True, help_text='Número de sello del flujómetro (Cargas internas)', null=True),
        ),
    ]
