# Generated by Django 4.2 on 2026-03-10 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_combustiblelog_sello_flujometro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_horas', models.PositiveIntegerField(default=200, help_text='Horas para mantención preventiva')),
                ('intervalo_km', models.PositiveIntegerField(default=10000, help_text='Kilómetros para mantención preventiva')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_mantencion', to='gestion.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Mantención',
                'verbose_name_plural': 'Configuraciones de Mantención',
            },
        ),
    ]
