# Generated by Django 4.2 on 2026-03-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_configuracionmantencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='firma_operador',
            field=models.TextField(blank=True, help_text='Firma digital guardada en Base64', null=True),
        ),
    ]
