# Generated by Django 4.2 on 2026-03-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_checklist_firma_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='correlativo',
            field=models.PositiveIntegerField(blank=True, help_text='Número correlativo interno por empresa', null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='nro_guia_despacho',
            field=models.CharField(blank=True, help_text='Número de documento manual (Opcional)', max_length=50, null=True),
        ),
    ]
