# Generated by Django 4.2 on 2026-03-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_ordentrabajo_correlativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Si True, el usuario será redirigido a cambiar su contraseña al iniciar sesión.'),
        ),
    ]
